language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install -e .
  - pip install coveralls pyyaml

script:
  - "coverage run --source=rtquery -m py.test"

after_success:
- coveralls